config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users

  root 'home#top'
  get 'home/about'

  get 'search' => 'searches#search'

  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers ,on: :member
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

def self.search(search, word)
	    if search == "forward_match"
	    	           @book = Book.where("title LIKE?","#{word}%")
	    elsif search == "backward_match"
	    	           @book = Book.where("title LIKE?","%#{word}")
	    elsif search == "perfect_match"
	    	            @book = Book.where("#{word}")
	    elsif search == "partial_match"
	    	            @book = Book.where("title LIKE?","%#{word}%")
	    else
	    	            @book = Book.all
	    end
	   end




def favorited_by?(user)
	favorites.where(user_id: user.id).exists?
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",foreign_key: :following_id
  has_many :followings, through: :active_relationships,source: :follower


  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
      passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search,word)
    if search == "forward_match"
                 @user = User.where("name LIkE?","#{word}%")
    elsif search =="backward_match"
                 @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                 @user = User.where("#{word}")
    elsif search == "partial_match"
                 @user = User.where("name LIKE?","%#{word}%")
    else
                @user = User.all
    end
  end

  #バリデーションは該当するモデルに設定:する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction,length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	def create
     @book = Book.find(params[:book_id])
     @book_comment = BookComment.new(book_comment_params)
     @book_comment.user_id = current_user.id
     @book_comment.book_id = @book.id
     @book_comment.save
 end

	def destroy
	  @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.find_by(id: params[:id], book_id: @book.id)
    @book_comment.destroy
  end

   private
   def book_comment_params
   	params.require(:book_comment).permit(:comment)
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book =Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
     if @book.user_id != current_user.id
        flash[:notice] = "error"
        redirect_to books_path
      end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body )
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @book.id)
		favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @book.id)
		favorite.destroy
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
 end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
  	@range = params[:range]
  	search = params[:search]
  	word = params[:word]

  	if @range == '1'
  	 @user = User.search(search,word)
  	else
  	 @book = Book.search(search,word)
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
end
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       flash[:notice] = "error"
       redirect_to user_path(current_user.id)
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end


   def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/index', book_comment: @book_comment) %>");
$(".form-control").val('');

app/views/book_comments/destroy.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/index', book_comment: @book_comment) %>");

app/views/books/_book.html.erb
                   <td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						 <%= book.user.name %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

                    <td>
					<% if book.favorited_by?(current_user) %>

					  <%= link_to book_favorites_path(book), method: :delete,remote: true do %>
					  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					  <%= book.favorites.count %>
					  <% end %>
					 <% else %>
					  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
                          <i class="fa fa-heart-o" aria-hidden = "true"></i>
                         <%= book.favorites.count %>
                      <% end %>
                    <% end %>
                    </td>

					<td><%= book.book_comments.count %>件のコメント</td>

app/views/books/_form.html.erb
<%= form_with(model: [@book, @book_comment]) do |f| %>
           <div>
            <%= f.text_area :comment, rows:'5', class: "form-control"%>
           </div>
           <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
           <% end %>

app/views/books/_index.html.erb
<% @book.book_comments.each do |book_comment| %>
            <div><%= book_comment.user.name %></div>
            <div><%= book_comment.comment %></div>
            <span>
            <% if book_comment.user == current_user %>
              	<%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true , class: "btn btn-danger pull-right" %>
              <% end %>
            </span>
            <% end %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
      </div>
      <% end %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr class="book_<%= book.id %>">
                <%= render 'books/book',book: book %>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>

					<td><% if @book.favorited_by?(current_user) %>
                        <%= link_to book_favorites_path(@book), method: :delete do %>
					    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
					    <%= @book.favorites.count %>
					   <% end %>
					    <% else %>
					    <%= link_to book_favorites_path(@book), method: :post do %>
                          <i class="fa fa-heart-o" aria-hidden = "true"></i>
                         <%= @book.favorites.count %>
                      <% end %>
                    <% end %>
                    </td>

					<td><%= @book.book_comments.count %>件コメント</td>

					<% if @book.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>

				</tr>
		</table>


            <h3>Comments</h3>
            <div class="book_<%= @book.id %>">
              <%= render 'books/index', book_comment: @book_comment %>
           </div>

           <h2>入力フォーム</h2>
           <%= render 'books/form', book_comment: @book_comment , book: @book %>
    </div>


	</div>
 </div>
</div>

app/views/favorites/create.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/book',  book: @book ) %>");

app/views/favorites/destroy.js.erb
$(".book_<%= @book.id %>").html("<%=j(render 'books/book',book: @book) %>");

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/searches/search.html.erb
<h1>検索結果一覧</h1>
<table>
	<% if @range == '2' %>
	<thead>
		<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
		<th colspan='3'></th>
	    </tr>
	</thead>

	<tbody>
		<% @book.each do |book| %>
		<tr>
		  <td>
		  	<%= link_to(book.user) do %>
		  	<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
		  	<% end %>
		  </td>
		  <td>
		  	<%= link_to book.title, book, class: "book_#{book.id}" %>
		  </td>
		  <td><%= book.body %></td>
		 </tr>
		 <% end %>
    </tbody>

    <% else %>
    <thead>
    	<tr>
    	<th>image</th>
    	<th>name</th>
    	<th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
    	<% @user.each do |user| %>

    	<tr>
    	<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
    	<td><%= user.name%></td>
    	<td><%= link_to "show",user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
    </tbody>
    <% end %>
</table>

app/views/users/_profile.html.erb
<p id="notice"></p>
<br>
<% if @book.errors.any? %>
    <div id="error_explanation" class="alert">
        <h2><%= @book.errors.count %>errors prohibited obj from being saved:</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
    </div>
<% end %>




<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
	   <th>follow</th>
	   <th><%= link_to follows_user_path(user.id) do %>
	   <%= "フォロー数: #{user.followings.count}" %>
	   <% end %>
	  </th>
	 </tr>

	<tr>
	   <th>follower</th>
	   <th><%= link_to followers_user_path(user.id) do %>
	   <%= "フォロワー数: #{user.followers.count}" %>
	   <% end %>
	   </th>
	</tr>
</table>
<div class="row">
	　<% if user.id == current_user.id %>
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

<% if current_user != user %>
 <% if user.followed_by?(current_user) %>
	<button><%= link_to"フォロー削除",user_relationships_path(user.id),method: :delete %></button>
	<% else %>
	<button><%= link_to "フォローする",user_relationships_path(user.id),method: :post %></button>
 <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<div class="container">
 <div class="row">
 <div class="col-xs-9">


<h1>follower覧</h1>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

<tbody>
<% @users.each do |user| %>
<tr>
  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
  <td><%= user.name %></td>
  <td><%= "フォロー数: #{user.followings.count}" %></td>
  <td><%= "フォロワー数: #{user.followers.count}" %></td>
  <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/follows.html.erb
<div class="container">
 <div class="row">
 <div class="col-xs-9">


<h1>follower覧</h1>

<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

<tbody>
<% @users.each do |user| %>
<tr>
  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
  <td><%= user.name %></td>
  <td><%= "フォロー数: #{user.followings.count}" %></td>
  <td><%= "フォロワー数: #{user.followers.count}" %></td>
  <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
 <div class="col-xs-3">
   <h2>User info</h2>
   <%= render 'users/profile', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/newform', book: @book %>
 </div>

<div class="col-xs-9">
 <h2>Users</h2>
<!--users一覧 -->
 <table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>

			<td><%= "フォロー数: #{user.followings.count}" %></td>
            <td><%= "フォロワー数: #{user.followers.count}" %></td>

             <% if current_user != user %>
             <% if user.followed_by?(current_user) %>
			 <td><%= link_to"フォロー削除",user_relationships_path(user.id),method: :delete %></td>
			 <% else %>
			 <td><%= link_to "フォローする",user_relationships_path(user.id),method: :post %></td>
			  <% end %>
			 <% end %>
              <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>






		</tr>
		<% end %>
	 </tbody>
    </table>
  </div>
 </div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
 <div class="container">
  <div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<%= @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= book.book_comments.count %>件のコメント</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
 </div>
</div>